//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
	public class A:B
	{
	public int  age;
		public A ()
		{
		 age = 10;
			Debug.Log ("A=" + this);
			
		}

	public override void test(){
		Debug.Log ("ATest");
	}
	}


