//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

	public class B
	{
		public B ()
		{
			Debug.Log ("B=" + this);
		}
		public virtual void test(){
		Debug.Log ("BTest");
		}
		

	static public System.Action<A> ChangeA = (A a) => {
		a.age = 25;
	};
//
//	static public void  changeA(A a){
//		a.age = 20;
//
//	}
	}


